# Generated by Django 4.0.6 on 2022-07-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0002_remove_order_img_path_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
